import { drawClock } from "./solution";

describe("Challenge #18: 🔢 The digital clock", () => {
  const testCases = [
    createTestCase(
      "01:30",
      [
        [
          "*",
          "*",
          "*",
          " ",
          " ",
          " ",
          "*",
          " ",
          " ",
          " ",
          "*",
          "*",
          "*",
          " ",
          "*",
          "*",
          "*",
        ],
        [
          "*",
          " ",
          "*",
          " ",
          " ",
          " ",
          "*",
          " ",
          " ",
          " ",
          " ",
          " ",
          "*",
          " ",
          "*",
          " ",
          "*",
        ],
        [
          "*",
          " ",
          "*",
          " ",
          " ",
          " ",
          "*",
          " ",
          "*",
          " ",
          " ",
          " ",
          "*",
          " ",
          "*",
          " ",
          "*",
        ],
        [
          "*",
          " ",
          "*",
          " ",
          " ",
          " ",
          "*",
          " ",
          " ",
          " ",
          "*",
          "*",
          "*",
          " ",
          "*",
          " ",
          "*",
        ],
        [
          "*",
          " ",
          "*",
          " ",
          " ",
          " ",
          "*",
          " ",
          "*",
          " ",
          " ",
          " ",
          "*",
          " ",
          "*",
          " ",
          "*",
        ],
        [
          "*",
          " ",
          "*",
          " ",
          " ",
          " ",
          "*",
          " ",
          " ",
          " ",
          " ",
          " ",
          "*",
          " ",
          "*",
          " ",
          "*",
        ],
        [
          "*",
          "*",
          "*",
          " ",
          " ",
          " ",
          "*",
          " ",
          " ",
          " ",
          "*",
          "*",
          "*",
          " ",
          "*",
          "*",
          "*",
        ],
      ],
      "should draw the digital clock for 01:30"
    ),
    // Add more test cases as needed
  ];

  it.each(testCases)("#$# $description", ({ input, expected, description }) => {
    expect(drawClock(input)).toEqual(expected);
  });
});

function createTestCase(input, expected, description) {
  return { input, expected, description };
}
